services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jira_backend
    restart: always
    environment:
      - DATABASE_SERVER=43.157.212.14
      - DATABASE_NAME=jira_clone
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=PasswordKamu123!
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - FRONTEND_URL=http://localhost
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jira_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
